name: Main branch CI

on:
  pull_request:
    branches:
      - main
    types: [closed]
  push:
    branches:
      - main
    
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - run: echo Valid!
        shell: bash
  
  version-bump:
    name: Calculate Version Bump
    env:
      # name of the triggering webhook event -- 'push' or 'pull_request"
      EVENT: ${{ github.event_name }}
      # for pull_request events, boolean indicating whether the PR was merged or not; otherwise empty string
      MERGED: ${{ github.event.pull_request.merged }}
    outputs:
      # type of SemVer version bump to use (major, minor, patch) or 'skip' if this event should not trigger CI
      type: ${{ steps.version.outputs.type }}
    runs-on: ubuntu-latest
    steps:
      - id: version
        run: |
          echo "event: ${EVENT} <<"
          echo "merged: ${MERGED} <<"
          if [ "${EVENT}" = "push" ]; then
            echo "::set-output name=type::patch"
          elif [ "${MERGED}" = "true" ]; then
            echo "::set-output name=type::minor"
          else
           echo "::set-output name=type::skip"
          fi
        shell: bash
        
  tag:
    name: Tag
    needs: [validate, version-bump]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.version-bump.outputs.tyhpe }}
        shell: bash
